Add Croatian translation
musa11971/Music-Bar pull request #61
Opened 2021-06-26 11:04 UTC by milotype

2021-07-14 10:21 UTC, musa11971 requested changes

2021-07-14 10:21 UTC, musa11971 commented on Music Bar/hr.lproj/Localizable.strings
> +"support_info" = "Ja sam redovni student softverskog inženjerstva i u slobodno vrijeme bavim se Music Barom. Ako voliš koristiti Music Bar, doniraj! Svaka donacija pomaže. 💜";
Is "Music Bar**om**" intentional here? I don't know Croatian, but because everywhere else you wrote "Music Bar" normally, this looks out of place

2021-07-15 12:57 UTC, milotype commented on Music Bar/hr.lproj/Localizable.strings
> +"support_info" = "Ja sam redovni student softverskog inženjerstva i u slobodno vrijeme bavim se Music Barom. Ako voliš koristiti Music Bar, doniraj! Svaka donacija pomaže. 💜";
Yes, it actually is intentional. In Croatian, names can be inflected/declinated (in this case it's the Croatian "instrumental" case).

2021-07-17 11:33 UTC, musa11971 commented
Thanks for your contribution! Will be added in the next update.

2021-07-17 11:33 UTC, merged